[project]
name = "indecision-notebooks"
version = "0.1.0"
description = "Notebooks for exploring indecision"
requires-python = ">=3.13"
dependencies = [
    "indecision",
]

[tool.uv.sources]
indecision = { path = "../", editable = true }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
